// <auto-generated />
using System;
using Frete.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Frete.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FreteDbContext))]
    [Migration("20260417153414_InitialFretePersistence")]
    partial class InitialFretePersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Frete.Domain.Entities.TabelaFrete", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("EmbarcadorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmbarcadorId");

                    b.HasIndex("EmbarcadorId", "Codigo")
                        .IsUnique();

                    b.ToTable("tabelas_frete", (string)null);
                });

            modelBuilder.Entity("Frete.Domain.Entities.TabelaFreteCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmbarcadorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocalidadeDestinoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocalidadeOrigemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TabelaFreteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("VigenciaFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("VigenciaInicio")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmbarcadorId");

                    b.HasIndex("TabelaFreteId");

                    b.HasIndex("EmbarcadorId", "TabelaFreteId");

                    b.HasIndex("EmbarcadorId", "LocalidadeOrigemId", "LocalidadeDestinoId");

                    b.ToTable("tabelas_frete_cliente", (string)null);
                });

            modelBuilder.Entity("Frete.Domain.Entities.TabelaFreteCliente", b =>
                {
                    b.HasOne("Frete.Domain.Entities.TabelaFrete", null)
                        .WithMany()
                        .HasForeignKey("TabelaFreteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
